# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: nest-pokemon
    volumes:
      - ./mongo:/data/db
